### ISSUE TITLE
Watching : [ 'www/js/*', '!www/css/**/*' ]

### ISSUE THREAD

**Issue by BekkamHareesh** [driftyco/ionic-platform-web-client#112]
I'm new to the ionic so please provide some workable solution, Please 
so this is the error.

Gulp startup tasks: [ 'sass', 'watch' ]
Running live reload server: http://localhost:35729
Watching : [ 'www/js/*', '!www/css/**/*' ]
Running dev server: http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ module.js:85
    throw e;
    ^

SyntaxError: Error parsing D:\HybridProjects\milkosoft\node_modules\gulp-sass\no
de_modules\gulp-util\node_modules\vinyl\package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:81:52)
    at tryPackage (module.js:91:13)
    at Function.Module._findPath (module.js:153:20)
    at Function.Module._resolveFilename (module.js:323:25)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\HybridProjects\milkosoft\node_modules\gulp-sass\no
de_modules\gulp-util\index.js:2:9)
    at Module._compile (module.js:409:26)

**Comment by dwieeb** [comment]
It looks like you're using the `ionic serve` command, which is part of the CLI? CLI issues can be posted in the [CLI repo](https://github.com/driftyco/ionic-cli/issues), but honestly it just looks like some weird npm issue that could be solved by reinstalling stuff.
