### ISSUE TITLE
Error running `ionic add ionic-platform-web-client`, related to phonegap-facebook-plugin dep

### ISSUE THREAD

**Issue by mattalexx** [driftyco/ionic-platform-web-client#127]
Terminal output's worth a thousand words (but let me know if you need some more words):
```
matt@miles ~/Projects/mobile (develop)
bower cache clean
bower deleted       Cached package ionic: /Users/matt/.cache/bower/packages/a6e3331f5b6a666502edb06e4d042783/1.2.4
bower deleted       Cached package ionic-platform-web-client: /Users/matt/.cache/bower/packages/19beef384deb83151dce7e015b23b5d1/0.7.1
matt@miles ~/Projects/mobile (develop)
ionic add ionic-platform-web-client



Bower error, check that "ionic-platform-web-client" exists,
or try running "bower install --save-dev ionic-platform-web-client" for more info. (CLI v1.7.16)

Your system information:

Cordova CLI: 6.2.0
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014



matt@miles ~/Projects/mobile (develop)
bower install --save-dev ionic-platform-web-client
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower ionic#1.2.4               cached git://github.com/driftyco/ionic-bower.git#1.2.4
bower ionic#1.2.4             validate 1.2.4 against git://github.com/driftyco/ionic-bower.git#1.2.4
bower ionic-platform-web-client#*           cached https://github.com/driftyco/ionic-platform-web-client.git#0.7.1
bower ionic-platform-web-client#*         validate 0.7.1 against https://github.com/driftyco/ionic-platform-web-client.git#*
bower phonegap-facebook-plugin#~0.12.0      ENOENT ENOENT: no such file or directory, stat '/Users/matt/Projects/phonegap-facebook-plugin'

Stack trace:
Error: ENOENT: no such file or directory, stat '/Users/matt/Projects/phonegap-facebook-plugin'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 5.8.0
OS: Darwin 15.5.0 x64
```

**Comment by dwieeb** [comment]
`phonegap-facebook-plugin` [isn't a dependency](https://github.com/driftyco/ionic-platform-web-client/blob/master/bower.json) of `ionic-platform-web-client`. 

Your error may be with this: `Error: ENOENT: no such file or directory, stat '/Users/matt/Projects/phonegap-facebook-plugin'`

**Comment by mattalexx** [comment]
Do you have any idea why it's looking for '/Users/matt/Projects/phonegap-facebook-plugin'? I don't see why it would, during the phonegap-facebook-plugin install.

**Comment by mattalexx** [comment]
Do you have any idea why it's looking for '/Users/matt/Projects/phonegap-facebook-plugin'? I don't see why it would, during the ionic-platform-web-client install.

**Comment by dwieeb** [comment]
What does your `bower.json` file say in the root of your project?

Perhaps bower preforms some sort of dependency validation during install.

**Comment by mattalexx** [comment]
Oh I found what must be dev code in the bower.json:
```
matt@miles ~/Projects/mobile (develop)
cat bower.json
{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.2.4",
    "phonegap-facebook-plugin": "../phonegap-facebook-plugin#~0.12.0"
  }
}
```
Thanks for the help.

**Comment by dwieeb** [comment]
You're welcome! 

That being said, I feel obliged to tell you we're moving away from bower and deprecating the `ionic-platform-web-client` soon. New projects should definitely be looking at the new [Cloud Client](https://github.com/driftyco/ionic-cloud), although it is not officially released yet and the current documentation is out of date.

**Comment by mattalexx** [comment]
I see. I'm running that command to install https://github.com/driftyco/ionic-plugin-deploy.

**Comment by dwieeb** [comment]
The cloud client (which is just an updated `ionic-platform-web-client`) works with `ionic-plugin-deploy`. That readme will be updated when the cloud client is fully released.

**Comment by mattalexx** [comment]
Oh, good to know.
