### ISSUE TITLE
Failed to instantiate module ionic.service.core

### ISSUE THREAD

**Issue by gtzinos** [driftyco/ionic-platform-web-client#135]
I follow this tutorial http://docs.ionic.io/v1.0/docs/io-service-modules#section-modifications

***ERROR***

ionic.bundle.js:17917 Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic.service.core due to:
Error: [$injector:nomod] Module 'ionic.service.core' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.3/$injector/nomod?p0=ionic.service.core
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13438:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:15404:17
    at ensure (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15328:38)
    at module (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15402:14)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17894:22
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17895:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=ionic.service.core&…%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17878%3A5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13438:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17917:15
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17895:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13691:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17878:5)
    at createInjector (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17800:19)
    at doBootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15080:20)
    at bootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15101:12)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=starter&p1=Error%3A…3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A15101%3A12)

**Comment by ericb** [comment]
The only way this can occur is if the bundle is not properly loaded, or the configuration is not injected properly into the bundle).  Make sure the script has properly been loaded, and that your config was written before moving to your custom app structure -- take special note of the `www/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js` path for configuration.

**Comment by gtzinos** [comment]
No. I found the problem. I had the root as owner of the bower .cache folder on my mac. I deleted this folder and the problem fixed.
