### ISSUE TITLE
ionic package Unexpected end of JSON input

### ISSUE THREAD

**Issue by louisdoe** [driftyco/ionic-platform-web-client#146]
Hi 

I have this issue when trying to  `ionic package build ios` my code.

Can you help me please ?

Thanks

```
$ ionic package info 194
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/home/louisro/.nvm/versions/node/v7.4.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/package.js:117:27)
    at Request.self.callback (/home/louisro/.nvm/versions/node/v7.4.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/louisro/.nvm/versions/node/v7.4.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/louisro/.nvm/versions/node/v7.4.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:1266:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by Laazarus** [comment]
Hello, 
I am having exactly the same problem..

`C:\Users\nic\Documents\CSC-patient-aide>ionic package info 13
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (C:\Users\nic\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\package.js:117:27)
    at Request.self.callback (C:\Users\nic\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\nic\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\nic\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\request\request.js:1266:12)
    at emitNone (events.js:91:20)

Mind letting us know? `https://github.com/driftyco/ionic-cli/issues`

Does anyone know what is the cause of this?

Regards

**Comment by Chris1234567899** [comment]
I can confirm this behavior. It was working sometimes well, but then I changed something in my config.xml (removed some plugins), and now the error occurs. The package build command returns still a success message that the package is beeing built, but later the package info command results in this error.

**Comment by piotrowski** [comment]
With the release of Ionic CLI v3 these errors should be gone (or different). Can you please recheck and close this issue if the are fixed?
